import Login from "../../PageObjects/FinancialPlannerPOM/LoginPage";
import Planner from "../../PageObjects/FinancialPlannerPOM/PlannerPage";
import Personal from "../../PageObjects/FinancialPlannerPOM/PersonalPage";

describe('Personal', () => {
    const loginSetup = () => {
        const LoginPage = new Login();
        const PlannerPage = new Planner();
        //const
        cy.visit('https://publicplan.aivante.net/New_FP/Dzee/financial_planner/planner');
        cy.fixture('FinancialPlanner').then((data) => {

            LoginPage.setEMailUserID("data.UserID");
            LoginPage.setPassword("data.Password");
            LoginPage.clickLogin();
            PlannerPage.setClient();
        })
  }
    beforeEach(() => {
        // Create/restore the session before each test
        cy.session('login', loginSetup, {
            validate: () => {
                cy.url().should('not.include', '/login');
            }
        });
        cy.visit('https://publicplan.aivante.net/New_FP/Dzee/financial_planner/planner#create_new_plan');
    });
     it('TC_FP_Personal_01: ClientEmail Personal Information', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
     });
  it('TC_FP_Personal_02:  FirstName', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");

  });
  it('TC_FP_Personal_03: Client LastName', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
     });

it('TC_FP_Personal_04: Client Gender', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    });
it('TC_FP_Personal_05: Client MonthofBirth', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
});
it('TC_FP_Personal_06: Client YearofBirth', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
});
it('TC_FP_Personal_07: Client HealthProfile', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
});
it('TC_FP_Personal_08: Client LifeExpectancy', () => {
    const PersonalPage = new Personal();
     PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
});
it('TC_FP_Personal_09: Client TobaccoUser', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
});
it('TC_FP_Personal_10: Client RetirementAge', () => {
    const PersonalPage = new Personal();
     PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
});
it('TC_FP_Personal_11: Client CurrentZipCode', () => {
    const PersonalPage = new Personal();
     PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
});
it('TC_FP_Personal_12: Client RetirementZipCode', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
    PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
});
it('TC_FP_Personal_13: Client TaxFilingStatus', () => {
    const PersonalPage = new Personal();
     PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
});
it('TC_FP_Personal_14: Client IncludeSpouse', () => {
    const PersonalPage = new Personal();
     PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
});
it('TC_FP_Personal_15: Client SpouseFirstName', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
});
it('TC_FP_Personal_16: Client SpouseLastName', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
    PersonalPage.setSpouseLastName("data.SpouseLastName");
});
it('TC_FP_Personal_17: Client SpouseGender', () => {
    const PersonalPage = new Personal();
     PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
    PersonalPage.setSpouseLastName("data.SpouseLastName");
    PersonalPage.setSpouseGender("data.SpouseGender");
});
it('TC_FP_Personal_18: Client SpouseMonthofBirth', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
    PersonalPage.setSpouseLastName("data.SpouseLastName");
    PersonalPage.setSpouseGender("data.SpouseGender");
    PersonalPage.setSpouseMonthofBirth("data.SpouseMonthofBirth");
});
it('TC_FP_Personal_19: Client SpouseYearofBirth', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
     PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
    PersonalPage.setSpouseLastName("data.SpouseLastName");
    PersonalPage.setSpouseGender("data.SpouseGender");
    PersonalPage.setSpouseMonthofBirth("data.SpouseMonthofBirth");
    PersonalPage.setSpouseYearofBirth("data.SpouseYearofBirth");
});
it('TC_FP_Personal_20: Client SpouseHealthProfile', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
    PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
    PersonalPage.setSpouseLastName("data.SpouseLastName");
    PersonalPage.setSpouseGender("data.SpouseGender");
    PersonalPage.setSpouseMonthofBirth("data.SpouseMonthofBirth");
    PersonalPage.setSpouseYearofBirth("data.SpouseYearofBirth");
    PersonalPage.setSpouseHealthProfile("data.SpouseHealthProfile");
});
it('TC_FP_Personal_21: Client SpouseLifeExpectancy', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
    PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
    PersonalPage.setSpouseLastName("data.SpouseLastName");
    PersonalPage.setSpouseGender("data.SpouseGender");
    PersonalPage.setSpouseMonthofBirth("data.SpouseMonthofBirth");
    PersonalPage.setSpouseYearofBirth("data.SpouseYearofBirth");
    PersonalPage.setSpouseHealthProfile("data.SpouseHealthProfile");
    PersonalPage.setSpouseLifeExpectancy("data.SpouseLifeExpectancy");
});
it('TC_FP_Personal_22: Client SpouseTobaccoUser', () => {
    const PersonalPage = new Personal();
    PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
    PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
    PersonalPage.setSpouseLastName("data.SpouseLastName");
    PersonalPage.setSpouseGender("data.SpouseGender");
    PersonalPage.setSpouseMonthofBirth("data.SpouseMonthofBirth");
    PersonalPage.setSpouseYearofBirth("data.SpouseYearofBirth");
    PersonalPage.setSpouseHealthProfile("data.SpouseHealthProfile");
    PersonalPage.setSpouseLifeExpectancy("data.SpouseLifeExpectancy");
    PersonalPage.setSpouseTobaccoUser("data.SpouseTobaccoUser");
});
it('TC_FP_Personal_23: Client SpouseRetirementAge', () => {
    const PersonalPage = new Personal();
     PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
    PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
    PersonalPage.setSpouseLastName("data.SpouseLastName");
    PersonalPage.setSpouseGender("data.SpouseGender");
    PersonalPage.setSpouseMonthofBirth("data.SpouseMonthofBirth");
    PersonalPage.setSpouseYearofBirth("data.SpouseYearofBirth");
    PersonalPage.setSpouseHealthProfile("data.SpouseHealthProfile");
    PersonalPage.setSpouseLifeExpectancy("data.SpouseLifeExpectancy");
    PersonalPage.setSpouseTobaccoUser("data.SpouseTobaccoUser");
    PersonalPage.setSpouseRetirementAge("data.SpouseRetirementAge");
});
it('TC_FP_Personal_24: Client SpouseCurrentZipCode', () => {
    const PersonalPage = new Personal();
     PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
    PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
    PersonalPage.setSpouseLastName("data.SpouseLastName");
    PersonalPage.setSpouseGender("data.SpouseGender");
    PersonalPage.setSpouseMonthofBirth("data.SpouseMonthofBirth");
    PersonalPage.setSpouseYearofBirth("data.SpouseYearofBirth");
    PersonalPage.setSpouseHealthProfile("data.SpouseHealthProfile");
    PersonalPage.setSpouseLifeExpectancy("data.SpouseLifeExpectancy");
    PersonalPage.setSpouseTobaccoUser("data.SpouseTobaccoUser");
    PersonalPage.setSpouseRetirementAge("data.SpouseRetirementAge");
    PersonalPage.setSpouseCurrentZipCode("data.SpouseCurrentZipcode");
});
it('TC_FP_Personal_25: Client SpouseRetirementZipCode', () => {
    const PersonalPage = new Personal();
      PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
    PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
    PersonalPage.setSpouseLastName("data.SpouseLastName");
    PersonalPage.setSpouseGender("data.SpouseGender");
    PersonalPage.setSpouseMonthofBirth("data.SpouseMonthofBirth");
    PersonalPage.setSpouseYearofBirth("data.SpouseYearofBirth");
    PersonalPage.setSpouseHealthProfile("data.SpouseHealthProfile");
    PersonalPage.setSpouseLifeExpectancy("data.SpouseLifeExpectancy");
    PersonalPage.setSpouseTobaccoUser("data.SpouseTobaccoUser");
    PersonalPage.setSpouseRetirementAge("data.SpouseRetirementAge");
    PersonalPage.setSpouseCurrentZipCode("data.SpouseCurrentZipcode");
    PersonalPage.setSpouseRetirementZipCode("data.SpouseRetirementZipcode");
});
it('TC_FP_Personal_26: Client Medicare', () => {
    const PersonalPage = new Personal();
      PersonalPage.setClientEmail("data.ClientEmail");
    PersonalPage.setFirstName("data.FirstName");
    PersonalPage.setLastName("data.LastName");
    PersonalPage.setGender("data.Gender");
    PersonalPage.setMonthofBirth("data.MonthofBirth");
    PersonalPage.setYearofBirth("data.YearofBirth");
    PersonalPage.setHealthProfile("data.HealthProfile");
    PersonalPage.setLifeExpectancy("data.LifeExpectancy");
    PersonalPage.setTobaccoUser("data.TobaccoUser");
    PersonalPage.setRetirementAge("data.RetirementAge");
    PersonalPage.setCurrentZipCode("data.CurrentZipcode");
    PersonalPage.setRetirementZipCode("data.RetirementZipcode");
    PersonalPage.setTaxFilingStatus("data.TaxFilingStatus");
    PersonalPage.clickIncludeSpouse();
    PersonalPage.setSpouseFirstName("data.SpouseFirstName");
    PersonalPage.setSpouseLastName("data.SpouseLastName");
    PersonalPage.setSpouseGender("data.SpouseGender");
    PersonalPage.setSpouseMonthofBirth("data.SpouseMonthofBirth");
    PersonalPage.setSpouseYearofBirth("data.SpouseYearofBirth");
    PersonalPage.setSpouseHealthProfile("data.SpouseHealthProfile");
    PersonalPage.setSpouseLifeExpectancy("data.SpouseLifeExpectancy");
    PersonalPage.setSpouseTobaccoUser("data.SpouseTobaccoUser");
    PersonalPage.setSpouseRetirementAge("data.SpouseRetirementAge");
    PersonalPage.setSpouseCurrentZipCode("data.SpouseCurrentZipcode");
    PersonalPage.setSpouseRetirementZipCode("data.SpouseRetirementZipcode");
    PersonalPage.clickMedicare();  // will click the Medicare tab
    PersonalPage.setTaxfillingstatusAlert();
});

});
